### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by zizzfizzix** [ninthz/laravel-epp#1]
Hi @ninthz, I was wondering if you didn't include a license for this code by mistake? I was pondering extending the code for another provider, but I'd feel more comfortable if the licensing was clear.

You can read about this more [here](https://choosealicense.com/no-license/) and [here](https://en.wikipedia.org/wiki/License-free_software).

Thanks!

**Comment by s-patompong** [comment]
Hi @zizzfizzix 

I'm sorry to tell you that this package is longer under maintenance. We spend a lot of time at the moment doing other things and we didn't have enough time to continue developing this package.

Please feel free to create a fork and use it at your disposal.
