### ISSUE TITLE
Issue in the EppClient.php

### ISSUE THREAD

**Issue by matt-smartlabs** [ninthz/laravel-epp#2]
Hi everyone,

I'm trying to implement this EPP library on my website, unfortunately I can't make it work. Currently I'm getting this error:

`fwrite() expects parameter 1 to be resource, null given`

in file vendor/ninthz/laravel-epp/src/EPP/EppClient.php - line 148

Do you know what I'm doing wrong?

**Comment by s-patompong** [comment]
Hi @matt-smartlabs 

I'm sorry to tell you that this package is longer under maintenance. We spend a lot of time at the moment doing other things and we didn't have enough time to continue developing this package.
